### PR TITLE
Added Banner Section & Update colour scheme

### PR DESCRIPTION
**Pull request by YuxinZhang214**
**Before this PR**
Screenshot 2023-10-28 at 17 09 22

**After this PR**
Screenshot 2023-10-28 at 16 49 21
- NRP is changed to a link but not reflected on this screenshot

Screenshot 2023-10-28 at 17 04 55

**Update**
- Added Banner Section with a denser pink.
- Update the sidebar to have a lighter pink
- Round border for all the section
- remove img for NRP

**Note**
- I was thinking about updating the entire colour scheme from white-pink to pink-purple, but i can't find how to update the main background colour. So the main bg colour is actually white.

### CODE REVIEW

**Comment by ozgurakgun** [comment]
should we have a meeting this week to go over these PRs?

**Comment by YuxinZhang214** [comment]
> should we have a meeting this week to go over these PRs?

Sure! I will email Xu and Daniel

**Comment by ozgurakgun** [comment]
Can you merge main into your pr please? I think your testing has been failing because this branch doesn't have the latest model fixes I made recently.

**Comment by YuxinZhang214** [comment]
> Can you merge main into your pr please? I think your testing has been failing because this branch doesn't have the latest model fixes I made recently.

Sure, sorry, I just saw this message. I've merged my changes and the main into this branch.

Now the banner looks like this.

Screenshot 2023-11-06 at 22 34 31

**Comment by YuxinZhang214** [comment]
Update Banner to 
Screenshot 2023-11-11 at 08 50 56

**Comment by ozgurakgun** [comment]
So the intention is that the Banner.tsx file in thei repo and the Banner.js in conjure-cp/task-allocation-demo#27 are equvalent, right?

Depending on framework other demos can reuse one of the two implementations.

Merging, thanks.

**Comment by YuxinZhang214** [comment]
> So the intention is that the Banner.tsx file in thei repo and the Banner.js in [conjure-cp/task-allocation-demo#27](https://github.com/conjure-cp/task-allocation-demo/pull/27) are equvalent, right?
> 
> Depending on framework other demos can reuse one of the two implementations.
> 
> Merging, thanks.

Yes! They are the same, the only difference is the .tsx one added the interface for the Banner object as is written in the typescript. (The config file can also be reused for typescript/javascript projects)

**Pull request merged**
